### PR TITLE
Create hide and show logic for joining list on Homepage

### LINKED ISSUE #54: Conditional logic showing list on Homepage

### PR DESCRIPTION
**Pull request by connietran-dev**
## Description

This adds logic on Home.js to show and hide the form for joining an existing list when you click "Join List". I moved the join-list-form into its own component. 

If there is a better way of doing this, I'm open to suggestion! I can also use some help with getting the CSS just right.

I also made some small changes so that the Homepage is getting closer to the wireframes, mostly by changing copy and getting rid of the <header> since we will be putting an image next to the text, adding our app logo, etc.

## Related Issue

Closes #54 : Conditional logic showing list on Homepage

## Acceptance Criteria

N/A - I didn't have time to write any in the ticket when we created it!

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|   | :sparkles: New feature     |
|  ✓  | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### Before

image

### After

Aug-29-2021 23-31-41

## Testing Steps / QA Criteria

1. Make sure you don't have a token so that you see the Homepage.
2. On the Homepage, you should see "Join List". 
2. When you click "Join List", the join list form appears with additional copy.
3. The button "changes" to "Join This List" instead of "Join List".

### CODE REVIEW

**Comment by anderswift** [comment]
I like the idea of having a separate component for the Join stuff we're adding, but am also thinking the way the markup is it will be hard to style and animate like the wireframe/mockups. Help me brainstorm how to rework it? We need the Create List and Join List buttons to be in the same container, and for the rest of the stuff to be wrapped in some container we can show/hide. Here's one suggestion off the top of my head that might work (but open to ideas):

```
<form>

  <div className={ /* add appropriate show/hide class based on showJoinForm state */}>
   /* form field and description go in here */
  </div>
  
  // Create must be type="button" if inside form!
  // make Create primary if not showJoinForm
  <button type="button" className={`button ${!showJoinForm ? 'button_type_primary' : ''}`}>
    Create List
  </button>
  
  // make Join primary if showJoinForm
  <button type="submit" className={`button ${showJoinForm ? 'button_type_primary' : ''}`} 
    onClick={(e) => { 
      if(!showJoinForm) {
        e.preventDefault(); // stop form submission
        setShowJoinForm(true); // change state to show token field
      } 
    }}
  >
      Join List
  </button>

</form>
```
I've simplified this a lot, but that's the gist of what comes to my mind.

**Comment by connietran-dev** [comment]
> I like the idea of having a separate component for the Join stuff we're adding, but am also thinking the way the markup is it will be hard to style and animate like the wireframe/mockups. Help me brainstorm how to rework it? We need the Create List and Join List buttons to be in the same container, and for the rest of the stuff to be wrapped in some container we can show/hide. Here's one suggestion off the top of my head that might work (but open to ideas):
> 
> ```
> <form>
> 
>   <div className={ /* add appropriate show/hide class based on showJoinForm state */}>
>    /* form field and description go in here */
>   </div>
>   
>   // Create must be type="button" if inside form!
>   // make Create primary if not showJoinForm
>   <button type="button" className={`button ${!showJoinForm ? 'button_type_primary' : ''}`}>
>     Create List
>   </button>
>   
>   // make Join primary if showJoinForm
>   <button type="submit" className={`button ${showJoinForm ? 'button_type_primary' : ''}`} 
>     onClick={(e) => { 
>       if(!showJoinForm) {
>         e.preventDefault(); // stop form submission
>         setShowJoinForm(true); // change state to show token field
>       } 
>     }}
>   >
>       Join List
>   </button>
> 
> </form>
> ```
> 
> I've simplified this a lot, but that's the gist of what comes to my mind.

@anderswift This is a great suggestion. I was struggling on how to keep the Create List and Join List buttons together. I've made a new commit to incorporate this change!

https://github.com/the-collab-lab/tcl-26-smart-shopping-list/pull/70/commits/0f2fbee4e6df5f1047146585e962f1dc706a3f41

**Comment by anderswift** [comment]
@connietran-dev I resolved the conflicts between our two branches so you don’t need to redo anything. Would be good though if you could add one little UX/a11y touch: put the focus on the form field once it is shown. I think all you would need to do is make a quick ref on that form field, then inside your onClick function that shows the join section add in:
`shareTokenRef.current.focus()`

**Review by anderswift — APPROVED** [review]
Looks great! I think we're ready to merge into main.

**Pull request merged**
